title:            Navneet Paul
subtitle:
description:      Navneet's Personal Website.
keywords:         robotics, reinforcement learning, imitation learning, machine learning, artificial intelligence,
language:         "en"
baseurl:          ""
url:              "http://nav74neet.github.io/"
permalink:        /blog/:categories/:title
cover:            /assets/machu_lacta.jpg
disqus_shortname: "nav74neet"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
